### ISSUE TITLE
Wiki Section for Development(?)

### ISSUE THREAD

**Issue by skip77** [rocky-linux/infrastructure#14945]
Hi, my name is Skip Grube.

There are several of us in the #rocky-devel-packaging channel on Slack that are working/thinking/prototyping about a core piece of Rocky Linux:  how to get the upstream sources into a form we can use, then rebuild them.

(See:  https://gitlab.com/SkipGrube/RockyLinux/-/blob/master/Build_Steps.md )

There's been a lot of discussion, some prototyping, and lots of links flying around.

We very much need a "Development" or "ReleaseEngineer" section of a Wiki somewhere that we are all allowed to contribute in.  Sharing links on Slack is great, but much gets lost after one discussion ends.  We're looking for somewhere permanent to dump these links/ideas, such as the .md above.

I don't much care what it's called, or where it lives, but... do we have the ability to do this?  We would like to limit ourselves to just that single "folder" in the Wiki.

Thanks!
-Skip Grube

**Comment by SherifNagy** [comment]
I have been collecting some info here too.. https://gitlab.com/sherif.nagy/rocky-linux and some packages audits in the mailing list https://groups.google.com/a/rockylinux.org/g/rocky-packaging and some other contributes keeps their findings in their gitlab, would be great to have a centralized wiki page:)

**Comment by nazunalika** [comment]
We will be reaching out to you and others directly for access to the wiki.

**Comment by nazunalika** [comment]
Right now we have given access to three so far. If there is data that we should add, please ping us in the packaging channel and we'll get it sorted out. Eventually we want to open up to a few more people as time moves forward.

**Comment by NeilHanlon** [comment]
Closing as resolved for now
