### ISSUE TITLE
Thiniking about contribution 

### ISSUE THREAD

**Issue by melezhik** [rocky-linux/infrastructure#14948]
Hi! I am thinking about contributing to the project. I have [my own](https://sparrowhub.io/) automation system. I know things are done here in ansible, but still curious if there is any  niche for automation like tasks in the project?

**Comment by rfelsburg-rockylinux** [comment]
At this point, we are sticking with ansible for our automation. While this may change for items in the future, at this point we are not considering any other automation systems for tasks.
