### ISSUE TITLE
Setting contribution guidelines for repository contributors

### ISSUE THREAD

**Issue by HeinKhantZaw** [rocky-linux/infrastructure#14951]
I think there should be CONTRIBUTING.md of how people should contribute to this repo.

**Comment by nazunalika** [comment]
The `README` of the `infrastructure/ansible` portion of this repo does talk about how to contribute already to the ansible portion, and what is expected. We will look into a contributors portion at the root.

**Comment by NeilHanlon** [comment]
Closing, duplicate of #1
