### ISSUE TITLE
[Bug Tracker] Enable SSO on Mantis Bug Tracker

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/infrastructure#14986]
Based on the [following ticket](https://bugs.rockylinux.org/view.php?id=6), we are looking to enable SSO with keycloak. SAML or OIDC both work and are acceptable. The plugin will have to be in PHP as the bug tracker is built with PHP (mantis bt). There are example plugins in the mantis github but they are not maintained or poorly documented.

**Comment by cybernet** [comment]
they fixed it mate :) they chose bugzilla ...
