### ISSUE TITLE
https://wiki.rockylinux.org/Infrastructure is not found

### ISSUE THREAD

**Issue by yifengyou** [rocky-linux/infrastructure#14991]
![image](https://user-images.githubusercontent.com/19882390/118265402-b7dd9b00-b4eb-11eb-9ffd-f9012bdb9996.png)

![image](https://user-images.githubusercontent.com/19882390/118240377-85bd4080-b4cd-11eb-984d-2fb4ac52833c.png)

**Comment by nazunalika** [comment]
Please see: https://wiki.rockylinux.org/team/infrastructure
