### ISSUE TITLE
where is /var/srpmproc/srpmproc_wrapper

### ISSUE THREAD

**Issue by yifengyou** [rocky-linux/infrastructure#15005]
Hi, 
     I found /var/srpmproc/srpmproc_wrapper in koji build, but there is no way to get it.

https://kojidev.rockylinux.org/kojifiles/work/tasks/1370/251370/root.log

![lQLPJxbqfiOMW8HNARHNAwewVpRn6uqnkEIDgUJbBECJAA_775_273](https://user-images.githubusercontent.com/19882390/204298792-a11fc7c3-fa50-427d-82f0-d7d03aa61b1f.png)

![lQLPJxbqfrRjMlHNAaXNB2Cw3HObW_wICaADgUNIJ0CFAA_1888_421](https://user-images.githubusercontent.com/19882390/204298754-0453c016-a632-486e-b13f-757bb0d3e4b4.png)

https://koji.rockylinux.org/koji/search?terms=srpmproc*&type=rpm&match=regexp

![image](https://user-images.githubusercontent.com/19882390/204303886-2ef86934-0b11-4945-b78e-291572432021.png)

![image](https://user-images.githubusercontent.com/19882390/204305450-c9de57ff-1ed5-4bcb-a7b6-ce0309501b3f.png)

![image](https://user-images.githubusercontent.com/19882390/204305670-7dff9e23-6798-4d8c-8335-36a1e483aeab.png)

maybe link  https://distrobuildstg.rockylinux.org/internal-repo/x86_64/Packages/srpmproc-0.1.0-2.x86_64.rpm

but , oops 404...

![image](https://user-images.githubusercontent.com/19882390/204306064-80a571d4-98ff-4b63-a0f6-1657cc752463.png)

**Comment by nazunalika** [comment]
This issue tracker is specifically for infrastructure tasks, not development. You are recommended to come to our mattermost, IRC or matrix rooms to ask srpmproc or koji specific questions.

In a koji build environment, it is expected that you create your own way to obtain the source tarballs of a package that is being built from a git repo. CentOS and Fedora do similar (centpkg, fedpkg, and so on). The srpmproc package is no different, providing a wrapper to pull down the sources. There is nothing special about this package and is specific to our environment.

```
INFO: Running in chroot: ['/var/srpmproc/srpmproc_wrapper']
Start: chroot ['/var/srpmproc/srpmproc_wrapper']
2022/11/28 16:41:39 downloading https://rocky-linux-sources-staging.a1.rockylinux.org/db930a6653503c36027a4f65d761f8838c7636ae
2022/11/28 16:41:40 downloading https://rocky-linux-sources-staging.a1.rockylinux.org/547c4e4afa06dd39c888a9ee89397ec3c3425c90
Finish: chroot ['/var/srpmproc/srpmproc_wrapper']
```

```
#!/bin/sh
/usr/bin/srpmproc fetch --cdn-url=https://rocky-linux-sources-staging.a1.rockylinux.org
```

```
Name:           srpmproc
Version:        0.1.0
Release:        2
Summary:        debrand/import
License:        MIT

Source0:        srpmproc-%{version}.tar.gz

%description

%prep
%setup -q

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/usr/bin
install -d $RPM_BUILD_ROOT/var/srpmproc
install srpmproc $RPM_BUILD_ROOT/usr/bin/srpmproc
install srpmproc_wrapper $RPM_BUILD_ROOT/var/srpmproc/srpmproc_wrapper

%clean
rm -rf $RPM_BUILD_ROOT

%files
%dir /var/srpmproc
%attr(0755, -, -) /usr/bin/srpmproc
%attr(0755, -, -) /var/srpmproc/srpmproc_wrapper
```

You will need to create your own package that contains the srpmproc binary and your own script.
