### ISSUE TITLE
[Enhancement] Ansible Playbooks - Network Time Protocol Client/Server

### ISSUE THREAD

**Issue by derekmpage** [rocky-linux/infrastructure#183]
I can work on this project. There are several in galaxy however none seem to support CentOS8

My recommendation:

- We use chrony rather then traditional NTP - https://chrony.tuxfamily.org/ 
    Chrony uses traditional NTP protocol but has extras to handle some worst case scenarios. 
    Chrony also allows us to run chrony server on virtual machines without the root_dispersion being trash. 

- We have a pair of chrony servers per site that pull from public source (ntp.org or whatever) 
   Then all of hosts/clients sync to the local servers with chrony client

- Chrony is just traditional NTP so network devices will be able to sync to the servers no problem.

- We don't need to achieve stratum 0 or anything... Stratum 3 will be perfectly acceptable.

**Comment by NeilHanlon** [comment]
I will get you ip addresses to plan on

**Comment by lionel-fernandes** [comment]
You can take a look at the rhel-system-roles.timesync / linux-system-roles.timesync.
It's the official role to configure both ntpd and chrony in RHEL/CentOS. If you need to extend its functionality it should be relatively easy.

**Comment by danielkubat** [comment]
@derekmpage for client installation/configuration, I recently published quite simple https://github.com/danielkubat/ansible-role-chrony, you may find it useful.
