### ISSUE TITLE
[Enhancement] Ansible Playbooks - Koji, GitLab EE, Pagure

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/infrastructure#184]
We will need playbooks that install Koji, GitLab EE, and Pagure. These will more than likely require roles to be pulled in from additional repos within rocky-linux, eg ansible-role-kojihub for example.

Pagure will likely need to be used with a messaging bus or we will need to build our own bus. The MBS communicates with both pagure and koji. GitLab does not support what Pagure/Koji/MBS do unless we make custom tooling.

**Comment by nasirhm** [comment]
I would like to work on it.

**Comment by NeilHanlon** [comment]
@nasirhm you are it sir. Would you like to go for both parts? We can split it if you'd like.

**Comment by nazunalika** [comment]
So I was working on some roles in the background for koji because it's a [complex beast](https://docs.pagure.org/koji/) and the installation can be [tricky](https://docs.pagure.org/koji/server_howto/), as we will need it to interact with FreeIPA. If you're willing to tackle it, by all means, please do! I can test the roles on some servers I have on hand.

Now, if you would like examples, here's the CentOS playbooks if you want to get an idea of what to do or expect. And be sure to read the koji documentation in the links above.

https://github.com/CentOS/ansible-role-kojid
https://github.com/CentOS/ansible-role-kojihub

So please let us know if you are willing to work on this.

As for **GitLab EE**, there is a [role right here](https://github.com/geerlingguy/ansible-role-gitlab) from a trusted source in galaxy. I'm going to test it out and add playbooks for it soon (after I complete one of my other roles).

**Comment by nasirhm** [comment]
> @nasirhm you are it sir. Would you like to go for both parts? We can split it if you'd like.

I would be more than happy to work on the Gitlab EE. I am wondering if we (@NeilHanlon) can work on the Koji one together ?

**Comment by NeilHanlon** [comment]
@nasirhm i will note Koji is something we need... Asap.

Re you comfortable being able to do that?

**Comment by nasirhm** [comment]
Sure, Build System is indeed a top priority. I can start working on it.

**Comment by NeilHanlon** [comment]
> > @nasirhm you are it sir. Would you like to go for both parts? We can split it if you'd like.
> 
> I would be more than happy to work on the Gitlab EE. I am wondering if we (@NeilHanlon) can work on the Koji one together ? 

We can definitely work in tandem.

Why don't you start on gitlab ee right now and we'll work on Koji altogether. Are you in slack?

**Comment by nasirhm** [comment]
Sure, Thank You :).

Joining Slack.

**Comment by nasirhm** [comment]
As we've got Playbook for Giltab merged, https://github.com/rocky-linux/infrastructure/pull/14947 I'm wondering to get started with writing Roles for Pagure and then Koji, what do you think @NeilHanlon @nazunalika

**Comment by nazunalika** [comment]
If you want to, I would focus on Koji for now. Pagure is still up in the air. 

Here's some references again:

https://github.com/CentOS/ansible-role-kojid
https://github.com/CentOS/ansible-role-kojihub

**Comment by nasirhm** [comment]
Sure, I can work on Koji first and then move to Pagure. :D 

Thank you for the references @nazunalika .

**Comment by nazunalika** [comment]
Hey @nasirhm! Sorry if this is like dropping a wrench into the gears... After some discussions I've had with some of the packaging folks and koji folks and doing some self-investigation, we have some architecture problems we need to solve first before we consider how we're going to make these roles and playbooks. (though we are curious of any progress)

In the mean time though, could you possibly work on a Pagure role instead? [This template](https://github.com/Darkbat91/ansible-roletemplate) is what we've been using for roles. And when you have something, could you let us know? I know Pagure is still left up in the air, but it is part of our koji architecture discussions.

Let me know if this works...

**Comment by nasirhm** [comment]
> Hey @nasirhm! Sorry if this is like dropping a wrench into the gears... After some discussions I've had with some of the packaging folks and koji folks and doing some self-investigation, we have some architecture problems we need to solve first before we consider how we're going to make these roles and playbooks. (though we are curious of any progress)

No worries, 

I agree, we need to focus on the architecture issues first and then we configure Koji. 

On the progress, I have gone through the roles in links you provided to get myself familiar with how the result playbooks would look like. :)

> In the mean time though, could you possibly work on a Pagure role instead? [This template](https://github.com/Darkbat91/ansible-roletemplate) is what we've been using for roles. And when you have something, could you let us know? I know Pagure is still left up in the air, but it is part of our koji architecture discussions.

Sure, Thank you very much for sharing the template.

> Let me know if this works...

I'm on it.

**Comment by fourstepper** [comment]
Pagure could be had from https://github.com/CentOS/ansible-role-pagure, perhaps?

**Comment by nazunalika** [comment]
Closing this as we have playbooks and roles that serve what we need.

https://github.com/rocky-linux/ansible-role-kojid
https://github.com/rocky-linux/ansible-role-kojihub
https://github.com/rocky-linux/ansible-role-rabbitmq
https://github.com/rocky-linux/infrastructure/blob/main/ansible/playbooks/rocky-rocky-gitlab-ee.yml
