### ISSUE TITLE
IP addressing plan

### ISSUE THREAD

**Issue by nicosalvadore** [rocky-linux/infrastructure#3]
Hello,

It is always important to define an IP addressing plan before starting to deploy servers and network infrastructure.
I saw on the FreeIPA inventory that you were using the subnet 10.100.1.0/24.

Has this been discussed in slack, IRC or on the forums ?

I'm asking because it would be best to think about it a bit before deploying base infrastructure like IPA, firewalls and VPNs.

For example we could reserve a supernet for each geographical zone. It eases network summarization.
- Europe - 10.128.0.0/12
- Americas - 10.144.0.0/12
- Asia - 10.160.0.0/12
- etc.

And then carve subnets in them to provision services.

Let me know what you think.

**Comment by nazunalika** [comment]
10.100.1.0/24 is not the subnet we decided on. That is a placeholder subnet that was being used for the lab and my internal testing before I pushed it up. It is by no means the end. Thank you for the suggestion on the subnets, we will be addressing it soon.

**Comment by amit177** [comment]
We should definitely have it organized by regions, however, we should have categories as well.
For example:

servers - 10.0.0.0/10
servers EU - 10.0.0.0/18
servers US - 10.0.64.0/18
p2p between sites - 
vpn clients -
backbone - 
etc

Whatever size would be assigned to the region can be broken down more as needed.

However, I'm not sure what would be easier to deal with, a big prefix for the region and then separated into categories or a big prefix for a category, and then that category can be separated into regions.

We should also have something similar for IPv6, (random global id with separation into regions and categories).

**Comment by NeilHanlon** [comment]
Let's go with 10.1.1.0/24 for The london nodes and 10.16.1.0/24 for the Phoenix nodes.

If I change the plan i'll change your playbooks :)

**Comment by nicosalvadore** [comment]
Better to summarize first by geographical zone, and then by roles. Because in the end, routing is bound to geographical requirements.

@NeilHanlon Shouldn't it be 10.0.1.0/24 if you'd like it to match the Phoenix nodes in term of addressing structure ?

**Comment by kevinsumner** [comment]
Dual-stack discussion was had on the forums: https://forums.rockylinux.org/t/ipv6-native-or-dual-stack/200/22

**Comment by codrcodz** [comment]
Hey folks. I've designed a few development networks before, and something I've done in the past that works well is giving servers matching fourth octets for each IP it has. For instance:

- 10.16.1.25/24 VLAN 2016 (Used on "public" VLAN open to all other internal VLANs)
- 172.16.1.25/24 VLAN 3016 (Used on "private" VLAN to communicate with HA clustered peers, servers of the same type, etc)
- 192.168.16.25 VLAN 4016 (Used on "inter-rack" VLAN for traffic not routed through cores/aggrs like DB replication, storage fail over, etc)

**Comment by codrcodz** [comment]
@NeilHanlon to elaborate on that a bit further, I took an excerpt from a reference architecture and engineer standards handbook I wrote for another project related to this topic and dropped it into a gist for review by the group; feel free to pull anything that works for the team from it: https://gist.github.com/codrcodz/be54fb5d4a46ba1f393db77c848bf366

**Comment by NeilHanlon** [comment]
> @NeilHanlon to elaborate on that a bit further, I took an excerpt from a reference architecture and engineer standards handbook I wrote for another project related to this topic and dropped it into a gist for review by the group; feel free to pull anything that works for the team from it: https://gist.github.com/codrcodz/be54fb5d4a46ba1f393db77c848bf366

Thanks Cody! 

Regarding standardizing ips across regions in v4 space, couldn't agree more.

We're dropping our mixtape^W ipv4 address plan. It should, I believe, also fall into line with PI v6 space when/if we get some to do dual stack. But dual stack is not important inside the DC right now. 

We are definitely adopting suggestions like yours, and appreciate them! Make sure you join us on slack and the forums. My brain is literally over full with all the conversations we have.
