### ISSUE TITLE
Licensing definition and COPYING file needed

### ISSUE THREAD

**Issue by ahappyyodeler** [rocky-linux/infrastructure#6]
This repository (along with many of the brand-new rocky-linux group) needs a license defined and COPYING file applied before many people can start contributing to or using them. I'm not sure what is an appropriate licence (GPL? Apache? MIT?), but without one, it is both ambiguous and many corporate entities assume "all rights reserved" without a clear open source license.

**Comment by nazunalika** [comment]
We'll likely use MIT. This is up to leadership.

**Comment by ahappyyodeler** [comment]
Closing this and moving to https://github.com/rocky-linux/rocky/issues/14 for a more unified top-level tracking.
